 # Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            motility
tagline:          'Tech nuggets by M Tegling'
description:      'by M Tegling'
url:              http://motility.se
baseurl:          /

author:
  name:           'Måns Tegling'
  url:            https://github.com/manstegling

paginate:         5

excerpt_separator: <!--end_intro-->

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/manstegling

linkedin:         https://www.linkedin.com/in/m%C3%A5ns-tegling-b20865138/

sass:
  sass_dir:  _sass
  style:     compressed